doctorsportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('patients/', views.patients_index, name='patients_index'),
    path('patients/<int:patient_id>/', views.patients_detail, name='patients_detail'),
    path('patients/create/', views.PatientsCreate.as_view(), name='patients_create'),
    path('patients/<int:pk>/update/', views.PatientsUpdate.as_view(), name='patients_update'),
    path('patients/<int:pk>/delete/', views.PatientsDelete.as_view(), name='patients_delete'),
    path('patients/<int:patient_id>/add_prescriptionsGiven/', views.add_prescriptionsGiven, name='add_prescriptionsGiven'),
    path('prescription/create/', views.PrescriptionsCreate.as_view(), name='prescriptions_create'),
    path('prescriptions/', views.PrescriptionsIndex.as_view(), name='prescriptions_index'),
    path('prescriptions/<int:pk>/', views.PrescriptionsDetail.as_view(), name='prescriptions_detail'),
    path('prescriptions/<int:pk>/update/', views.PrescriptionsUpdate.as_view(), name='prescriptions_update'),
    path('prescriptions/<int:pk>/delete/', views.PrescriptionsDelete.as_view(), name='prescriptions_delete'),
    path('patients/<int:patient_id>/assoc_prescription/<int:prescription_id>/', views.assoc_prescription, name='assoc_prescription'),
    path('patients/<int:patient_id>/remove_prescription/<int:prescription_id>/', views.remove_prescription, name='remove_prescription'),
    path('patients/<int:patient_id>/add_photo/', views.add_photo, name='add_photo'),
    path('patients/<int:patient_id>/delete_photo/<int:pk>/', views.PhotoDelete.as_view(), name='delete_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from random import choices
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Prescription(models.Model):
    name = models.CharField(max_length=100)
    dosage = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name} {self.dosage}'
    
    def get_absolute_url(self):
        return reverse('prescriptions_detail', kwargs={'pk': self.id})

class Patient(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    gender = models.CharField(max_length=100)
    chief_complaint = models.CharField(max_length=500)
    current_condition = models.TextField(max_length=500)
    past_medical_history = models.TextField(max_length=500)
    prescriptions = models.ManyToManyField(Prescription)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

def __str__(self):
    return self.name

def get_absolute_url(self):
    return reverse('patients_detail', kwargs={'patient_id': self.id})

class Prescriptions_Given(models.Model):
    PRESCRIPTIONS_GIVEN = (
        ('P', 'Pain Medication'),
        ('A', 'Anitbiotics'),
        ('F', 'Fluids'),
    )

    class Meta:
        ordering = ('-date', '-time')

    date = models.DateField('Prescription Date')
    time = models.TimeField(auto_now=False, auto_now_add=False)
    prescriptionsGiven = models.CharField(max_length=1, choices=PRESCRIPTIONS_GIVEN, default=PRESCRIPTIONS_GIVEN[0][0])
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_prescriptionsGiven_display()} on {self.date} at {self.time}'

class Photo(models.Model):
    url = models.CharField(max_length=200)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for patient_id: {self.patient_id} @{self.url}'

main_app/forms.py
from django.forms import ModelForm
from .models import Prescriptions_Given

class PrescriptionsGivenForm(ModelForm):
    class Meta:
        model = Prescriptions_Given
        fields = ('date', 'time', 'prescriptionsGiven')

main_app/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render, redirect
from django.urls import reverse

from .models import Patient, Prescription, Photo

from django.contrib.auth import login

from .forms import PrescriptionsGivenForm
from django.contrib.auth.forms import UserCreationForm

import boto3
import uuid 

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'doctors-portal-p4'


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def patients_index(request):
    patients = Patient.objects.filter(user=request.user)
    return render(request, 'patients/index.html', {'patients': patients})

@login_required
def patients_detail(request, patient_id):
    patient = Patient.objects.get(id=patient_id)
    prescriptionsGiven_form = PrescriptionsGivenForm()
    prescriptions = Prescription.objects.exclude(id__in = patient.prescriptions.all().values_list('id'))
    return render(request, 'patients/detail.html', 
    { 
        'patient': patient,
        'prescriptionsGiven_form': prescriptionsGiven_form, 
        'prescriptions': prescriptions 
    })

@login_required
def add_prescriptionsGiven(request, patient_id):
    form = PrescriptionsGivenForm(request.POST)
    if form.is_valid():
        new_prescriptionsGiven = form.save(commit=False)
        new_prescriptionsGiven.patient_id = patient_id
        new_prescriptionsGiven.save()
    else:
        print(form.errors)
    return redirect('patients_detail', patient_id=patient_id)

def assoc_prescription(request, patient_id, prescription_id):
    Patient.objects.get(id=patient_id).prescriptions.add(prescription_id)
    return redirect('patients_detail', patient_id=patient_id)

def remove_prescription(request, patient_id, prescription_id):
    Patient.objects.get(id=patient_id).prescriptions.remove(prescription_id)
    return redirect('patients_detail', patient_id=patient_id)

def add_photo(request, patient_id):
    photo_file = request.FILES.get('photo-file')
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key) 
            url = f'{S3_BASE_URL}{BUCKET}/{key}'
            photo = Photo(url=url, patient_id=patient_id)
            photo.save()
        except Exception as error:
            print('An error has occured uploading or saving the photo')
            print(error)
    return redirect('patients_detail', patient_id=patient_id)

def signup(request):
    error_message = None
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('patients_index')
        else:
            error_message = 'Signup input invalid - Please try again'
    form = UserCreationForm()
    context = { 'form': form, 'error': error_message }
    return render(request, 'registration/signup.html', context)

class PatientsCreate(LoginRequiredMixin, CreateView):
    template_name= 'patients/patient_form.html'
    model = Patient
    fields = ['name', 'age', 'gender', 'chief_complaint', 'current_condition', 'past_medical_history']
    success_url = '/patients/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PatientsUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'patients/patient_form.html'
    model = Patient
    fields = ['chief_complaint', 'current_condition', 'past_medical_history']
    success_url = '/patients/'

class PatientsDelete(LoginRequiredMixin, DeleteView):
    model = Patient
    success_url = '/patients/'

class PrescriptionsCreate(LoginRequiredMixin, CreateView):
    template_name = 'prescriptions/prescription_form.html'
    model = Prescription
    fields = ('name', 'dosage')
    
class PrescriptionsIndex(LoginRequiredMixin, ListView):
    template_name = 'prescriptions/index.html'
    model = Prescription 

class PrescriptionsDetail(LoginRequiredMixin, DetailView):
    template_name = 'prescriptions/detail.html'
    model = Prescription 
    
class PrescriptionsUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'prescriptions/prescription_form.html'
    model = Prescription
    fields = ('name','dosage')
    
class PrescriptionsDelete(LoginRequiredMixin, DeleteView):
    model = Prescription
    success_url = '/prescriptions/'

class PhotoDelete(LoginRequiredMixin, DeleteView):
    model = Photo

    def get_success_url(self):
        return reverse('patients_detail', kwargs={'patient_id': self.object.patient_id})

main_app/templates/patients/detail.html
{% extends 'base.html' %}

{% block title %}

Information for {{ patient.name }} | Doctor's Portal

{% endblock %}

{% block content %}

<h1>Patient Info</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ patient.name }}</span>
        {% if patient.age > 0 %}
        <p>Age: {{ patient.age }}</p>
        {% else %}
        <p>Age: Infant</p>
        {% endif %}
        <p>Gender: {{ patient.gender }}</p>
        <p>Chief Complaint: {{ patient.chief_complaint }}</p>
        <p>Current Condition: {{ patient.current_condition }}</p>
        <p>Past Medical History: {{ patient.past_medical_history }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'patients_update' patient.id %}">Edit</a>
        <a href="{% url 'patients_delete' patient.id %}">Delete</a>
      </div>
    </div>

        {% for photo in patient.photo_set.all %}
        <img class="responsive-img" 
        src="{{ photo.url }}" 
        alt="{{ patient.name }}"
        />
        <form action="{% url 'delete_photo' patient.id photo.id %}" method="POST">
          {% csrf_token %}
          <input type="submit" class="btn red" value="delete">
        </form>

    {% empty %}
        <div class="card-panel blue-text center-align">
          No Files Uploaded
        </div>
    {% endfor %}
    <form 
      action="{% url 'add_photo' patient.id %}"
      method="POST"
      class="card-panel"
      enctype="multipart/form-data"
    >
        {% csrf_token %}
        <input type="file" name="photo-file" />
        <br />
        <br />
        <input type="submit" value="Upload Photo" class="btn blue" />
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_prescriptionsGiven' patient.id %}" method="POST">
      {% csrf_token %}
      {{ prescriptionsGiven_form.as_p }}
      <input type="submit" class="btn blue" value="Add Prescriptions Given" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>Prescriptions Given</th>
        </tr>
      </thead>
      <tbody>
        {% for prescriptiongiven in patient.prescriptions_given_set.all %}
        <tr>
          <td>{{ prescriptiongiven.date }}</td>
          <td>{{ prescriptiongiven.time }}</td>
          <td>{{ prescriptiongiven.get_prescriptionsGiven_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr />

<div class="row">
  <div class="col s6">
    <h3>{{ patient.name }} Prescription</h3>
    {% if patient.prescriptions.count %} {% for prescription in patient.prescriptions.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
           {{ prescription.name.capitalize }} {{ prescription.dosage }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'remove_prescription' patient.id prescription.id %}" method="POST">
          {% csrf_token %}
          <input class="" type="submit" value="Remove">
        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>{{ patient.name }} has no prescriptions</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Prescriptions</h3>
    {% if prescriptions.count %}
      {% for prescription in prescriptions.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
          {{ prescription.name.capitalize}} {{ prescription.dosage }} 
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_prescription' patient.id prescription.id %}" method="POST">
            {% csrf_token %}
            <input class="" type="submit" value="Add">
          </form>
        </div>
      </div>
      {% endfor %}
    {% else %}
    <h5>{{ patient.name }} has all available prescriptions</h5>
    {% endif %}
  </div>
</div>


<script>
  const dateField = document.getElementById('id_date');
  const timeField = document.getElementById('id_time');
  const prescriptionGivenSelect = document.getElementById('id_prescriptionsGiven');

  M.Datepicker.init(dateField, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  M.Timepicker.init(timeField, {
    defaultTime: 'now',
    twelveHour: false
  });

  M.FormSelect.init(prescriptionGivenSelect);
</script>  
  


{% endblock %}

main_app/templates/patients/index.html
{% extends 'base.html' %}

{% block title %}
Current Patients | Doctor's Portal
{% endblock %}

{% block content %}
<h1>Current Patients</h1>

{% for patient in patients %}
<a href="{% url 'patients_detail' patient.id %}"> 
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ patient.name }}</span>
            {% if patient.age > 0 %}
            <p>Age: {{ patient.age }}</p>
            {% else %}
            <p>Age: Infant</p>
            {% endif %}
            <p>Gender: {{ patient.gender }}</p>
            <p>Chief Complaint: {{ patient.chief_complaint }}</p>
            <p>Current Condition: {{ patient.current_condition }}</p>
            <p>Past Medical History: {{ patient.past_medical_history }}</p>
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/patients/patient_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add A Patient</h1>
{% endif %}

<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="{% if object %} Edit {%else %} Add Patient {% endif %}" class="btn green" />
</form>
{% endblock %}